name: paths-bookmarks
version: 0.1.0.0
github: "sproott/pat.hs"
license: BSD3
author: "sproott"
maintainer: "david.hrabe12@seznam.cz"
copyright: "2021 sproott"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sproott/pat.hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - either
  - extra
  - filepath
  - megaparsec
  - optparse-applicative
  - polysemy
  - polysemy-plugin
  - prettyprinter
  - prettyprinter-ansi-terminal
  - protolude
  - relude
  - text
  - transformers
  - unix
  - xdg-basedir

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies

library:
  source-dirs: src

ghc-options:
  - -Wunused-imports
  - -O2 -flate-specialise -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin

executables:
  paths:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - paths-bookmarks

tests:
  paths-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - paths-bookmarks
      - explainable-predicates
      - tasty
      - tasty-hunit
