name: pat-hs
version: 0.1.0.0
github: "githubuser/pat-hs"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/pat-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - either
  - extra
  - filepath
  - megaparsec
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - safe
  - text >= 1.2.5.0
  - transformers

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src

executables:
  pat-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wunused-imports
    dependencies:
      - pat-hs

tests:
  pat-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pat-hs
