#!/usr/bin/env bash

dir="/usr/share/paths"

paths() {
  if [ $1 = "go" ]; then
    cd "$(\"$dir/paths-exe\" go $2)";
  else
    "$dir/paths-exe" "$@";
  fi
}

complete -o filenames -F _paths-exe paths
