name: test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1.2
        with:
          enable-stack: true
          stack-no-global: true
      - run: stack test

